### ISSUE TITLE
Add a warning message if the different files within a zip folder do NOT contain identical columns

### ISSUE THREAD

**Issue by makostadima** [tercen/read_csv_operator#1]
When this operator is used to upload multiple files from a .zip file then these are concatenated into a single dataset.

The files need to have identical headers for the concatenation to take place without issues.

Is there a way that the operator throws a warning, if that's not the case? It could save our users a lot of trouble downstream, if that happens early on in the process.

And is there a use case where different headers are acceptable for this operator?

**Comment by agouy** [comment]
Fixed in v 0.1.4
